use clap::{Arg, App};

pub fn create_cli_app() -> App<'static,'static> {
  App::new("lookup-service")
    .version("0.1.0")
    .author("Bryan G. <bryan@bryan.codes>")
    .about("A HTTP simple service that can lookup information about IP addresses.")
    .arg(Arg::with_name("host")
         .long("host")
         .help("Host to bind service to.")
         .default_value("0.0.0.0")
         .takes_value(true))
    .arg(Arg::with_name("port")
         .short("-p")
         .long("port")
         .help("Port to bind service to.")
         .default_value("8080")
         .takes_value(true))
    .arg(Arg::with_name("maxmind-city-database")
         .long("maxmind-city-database")
         .help("Maxmind city database file.")
         .required(true)
         .takes_value(true))
    .arg(Arg::with_name("asn-database")
         .long("asn-database")
         .help("Asn database file.")
         .required(true)
         .takes_value(true))
    .arg(Arg::with_name("ip2asn-database")
         .long("ip2asn-database")
         .help("ip2asn database file.")
         .required(true)
         .takes_value(true))
}
